syntax = "proto3";

package auth;
option go_package = "guide.auth.v1;authv1";

service Auth {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc Logout (LogoutRequest) returns (LogoutResponse);
    rpc SendVerifyEmail (SendVerifyRequest) returns (SendVerifyResponse);
    rpc VerifyEmail (VerifyEmailRequest) returns (VerifyEmailResponse);
}

message RegisterRequest {
    string email = 1;
    string password = 2;
}

message RegisterResponse {
    int64 user_id = 1;
}

message LoginRequest {
    string email = 1;
    string password = 2;
    int32 app_id = 3;
}

message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message LogoutRequest {
    string token = 1;
}

message LogoutResponse {
    bool success = 1;
}

message SendVerifyRequest {
    string email = 1;
}

message SendVerifyResponse {
    bool sent = 1;
}

message VerifyEmailRequest {
    string verification_token = 1;
}

message VerifyEmailResponse {
    bool verified = 1;
}